name: 'fluxctl'
description: 'A GitHub Action to run fluxctl commands against a Kubernetes cluster'
author: 'Stefan Prodan'
branding:
  icon: 'command'
  color: 'blue'
runs:
  using: 'docker'
  image: './src/Dockerfile'
